### ISSUE TITLE
Control behaviour change based on the dependent attribute of the model

### ISSUE THREAD

**Issue by asheshv** [AmiliaApp/backform#25]
Hi [Martin Drapeau](https://github.com/martindrapeau),

The current implementation does allow to change the value of required, disabled attributes, when any other attribute of the model gets changes. In short - it does not support any type of dependency.

In this pull request #24, I've try to implement it by introducing two new attributes in Field (i.e. deps, visible).
You can use deps as array of name of the attributes on which this field is dependent.

And also, allow the required, and disabled (and, new attribute 'visible') to take boolean value or, a function returning a boolean value.

Now - when the dependent attribute(s) get(s) changed, render function of the Control will be called.
And, required, visible, and disabled will be evaluated at that time.

I've also modified the documents with examples.

Please have a look at it, and give me your feedback.

**Comment by martindrapeau** [comment]
This issue is really about two-way binding. Here's a [good Stack Overflow about it](http://stackoverflow.com/questions/13504906/what-is-two-way-binding).

Currently Backform performs view-model binding - DOM changes modify the model. However it lacks model-view bindings - model changes do not automatically percolate to the DOM. It was built this way to stay at par with the Backbone philosophy. On a parallel note, the [same discussion has happened on Backbone Marionette](https://github.com/marionettejs/backbone.marionette/issues/852).

In your pull request you do make model-view binding optional and granular (per attribute) which is nice. I don't like that it is set in a model attribute. Maybe we can implement a class property [modelEvents just like in Marionette](http://marionettejs.com/docs/marionette.view.html#viewmodelevents-and-viewcollectionevents). Would be more powerful and could be used for other things than just rendering. In your case you could simply do:
```
Backform.InputControl.extend({
modelEvents: {
  "change:toggle": "render"
},
...
});
```

And of course, if you want all controls to have model-view bindings in your code, you can do this:
```
Backform.Control.prototype.modelEvents = {
  "change": "render"
};
```
What do you think?

**Comment by app** [comment]
Hi!
I think it will be nice to have some form of model-view binding. 
And Marionette way is better than nothing.
