### ISSUE TITLE
Input File Type?

### ISSUE THREAD

**Issue by sphildreth** [AmiliaApp/backform#57]
How would one add the ability to upload a file with the form? Generate some HTML like:

    <input type="file" accept=".png" class="input" id="avatar" name="avatar"/>

**Comment by martindrapeau** [comment]
You can se type:
```
fields = {
    {name: "avatar", label: "Upload a file", control: "input", type: "file"}
};
```
But that will only give you the file name.

Uploading a file is not that simple. You can do it separately than your Backform. Using [Croppie](http://foliotek.github.io/Croppie/) or something similar.

If you are adventurous, you could create an InputFile control. It would use HTML5's [FileReader](https://developer.mozilla.org/en/docs/Web/API/FileReader) to read and encode it to a base64 string. You could then set it on a model attribute. When you do model.save(), it would be sent. Your backend could then decode the base64 string and store the image binary.

If you're even more adventurous, you could create a CroppieInput control that allows the user to crop the image first. That would be really cool.

Since you are working with avatars which are typically small image files, both approaches would work great. If you do go that route, please make a pull request to integrate back your change. The community would greatly appreciate.
