### ISSUE TITLE
Backform.Form render() cause TypeError: this.listenTo is not a function

### ISSUE THREAD

**Issue by johnstile** [AmiliaApp/backform#62]
Using:  Jquery-1.12.4, Underscore.js 1.8.3, Backbone.js 1.3.3

Using Backform in a modular backbone + requirejs app,  render() leads to
backform.js:262 Uncaught TypeError: this.listenTo is not a function

In the code below, I trap the button click, to call show_conf_form(), which basically uses same code in the example, but mine doesn't work.

Am I doing something wrong, or running into a version incompatibility issue?

I don't understand the error.
--------------------------------------------
define([ 'jquery', 'underscore',  'backbone', 'backform', 'collections/configs/ConfigsCollection', 'text!templates/configs/configsTemplate.html'
], function ($, _, Backbone, Backform, ConfigsCollection, configsTemplate) {
    var ConfigsView = Backbone.View.extend({
        el: $("#page"),
        events: {
            "click #conf-edit-button": "show_conf_form"
        },
        initialize: function () {
            var that = this;
            var onErrorHandler = function (collection, response, options) {
                alert(response.responseText);
            };
            var onDataHandler = function (collection, response, options) {
                that.render();
            };
            that.collection = new ConfigsCollection([]);
            that.collection.fetch({success: onDataHandler, error: onErrorHandler});
        },
        render: function () {
            // Menu
            $('.menu li').removeClass('active');
            $('.menu li a[href="' + window.location.hash + '"]').parent().addClass('active');
            var data = {
                confs: this.collection.models,
                _: _
            };
            // main view
            var compiledTemplate = _.template(configsTemplate, data);
            this.$el.html(compiledTemplate);
        },
        show_conf_form: function () {
            console.log("calling  show_conf_form");
            // TOY PERSON
            var person = new Backbone.Model({
                id: 101,
                firstName: "Annie",
                lastName: "Employee"
            });
            // TOY FIELDS
            var formFields = [
                {name: "id", label: "Id", control: "uneditable-input"},
                {name: "firstName", label: "First Name", control: "input"},
                {name: "lastName", label: "Last Name", control: "input"},
                {name: "submitButton", label: "Save to server", control: "button"}
            ];
            // Instantiate the form
            var form = new Backform.Form({
                el: $("#form"),
                fields: formFields,
                model: person
            });
            // ERROR HERE
            form.render();
        }
    });
    return ConfigsView;
});

**Comment by mnormand** [comment]
I think you are missing return this; at the end of the render function

**Comment by johnstile** [comment]
return this; at the end of the render function has no effect on the error.

**Comment by patattackziliko** [comment]
if you comment out el: $("#page") in your definition it should work
Note that I tested this with backbone marionnet and I did not have your template so I created a simple text template and it rendered.
I also commented out your collection fectching just to see if that worked.
What I think is happening is that your model is undefined somehow


      that.collection = new Backbone.Collection.extend({
        model: new Backbone.Model.extend({
          defaults: {
            id: 0,
            firstname: '',
            lastname:''
          }
        })
      });

I tested it with this as a empty test and it worked. so the problem is how the model is being passed to your view. make sure there is an instance.

**Comment by jdhorner** [comment]
@johnstile I've created a [jsfiddle](https://jsfiddle.net/jdhorner/t8fs4838/3/). Check it out to see a working example. Everything seems to work for me, with the most basic of configurations. 

jquery + underscore + backbone + backform

The error your console is reporting is when each control within the form gets initialized, where they are bound to the model attribute for that control for changes.
```javascript
      // Listen to the field in the model for any change
      this.listenTo(this.model, 'change:' + name, this.render);
```
if `this.listenTo()` is not a function, then it would appear that somehow context has gotten lost, or something else is going on. 

Please feel free to edit the JSFiddle with more information and/or code examples, or, port more of your project into your own JSFiddle so perhaps we can see more of what's going on. (Otherwise, I see no bug here)

**Comment by johnstile** [comment]
patattackziliko: Commenting out el: $("#page") in your definition, causes nothing to appear.
jdhorner:  I think you are on the right track, that my model instance is lost/invalid.  This is probably a problem using a modularized system with requirejs.
i used your jsfiddle, but have 2 types of errors
  if view ends in:    new ConfigsView().render();
  error:       router.js:47 Uncaught TypeError: ConfigsView is not a constructor
  If view ends in:   return ConfigsView;
  And I click the button, 
  error:    backform.js:262 Uncaught TypeError: this.listenTo is not a function

In router.js, when one clicks the Config button it calls this:
        app_router.on('route:showConfigs', function () {
            var configsView = new ConfigsView();
            configsView.render();
        });

**Comment by jdhorner** [comment]
@johnstile My fiddle won't work if it's simply pasted back into your own code because I removed all of the requireJS code. Rather than returning the ConfigsView directly, I just rendered it directly as an example. You can put back your `return ConfigsView;` code in place of my `new ConfigsView().render();`

Regardless, I just don't know how else to help you troubleshoot what's going on. 

Is your project on github?

**Comment by johnstile** [comment]
I uploaded my code to https://github.com/johnstile/jobinterface
This does not have your fiddle bits, but maybe it is clear what is wrong.
I noticed the tutorial I followed follows a pattern of make instance, then call render().  Your style is to have the view's return call new and render().  I have tried it both ways, without success. But my objects are probably not instantiated correctly for Backform.  I also included a sample_data directory with the json of the collections.

**Comment by johnstile** [comment]
Finally have it working using the toy data.  I accidentally had an old version of backbone, where listento() did not exist.  Also had an old version of underscore, so I had to update the _.template() syntax.  After that Backform works for me.  Now I need to make it work with my real data.  Thank you for your help.

**Comment by jdhorner** [comment]
@johnstile thanks for the update! Glad to hear you've gotten it working for now!

**Comment by johnstile** [comment]
Where should I ask general questions about Backfrom? 
I would like to poplate a form with:   JSON.stringify(mymodel.get("conf"))
I have no control over the schema of conf in my model.
I'd like to just let the user edit as they wish.
Where should I ask such a question?
